/* This file is generated by vite.config.ts. Do not edit dist/sw.js directly. */
const CACHE_PREFIX = "bongest-worker-precache-";
const CACHE_NAME = `${CACHE_PREFIX}18c0f641db12`;
const PRECACHE_URLS = [
  "/assets/WorkerApp-CySIpoNr.js",
  "/assets/arrow-left-ByNDS6Am.js",
  "/assets/clock-BSQfcoMG.js",
  "/assets/format-DDtTmspW.js",
  "/assets/fr-C7FHZUZ9.js",
  "/assets/image-BBubpbGv.js",
  "/assets/interventionReferences-rTpzSBNm.js",
  "/assets/isToday-CuOGN-Ps.js",
  "/assets/loader-circle-b2foremB.js",
  "/assets/main-BR7qWsyq.js",
  "/assets/main-CNMGtfHj.css",
  "/assets/package-DCoU28jt.js",
  "/assets/phone-Cl5mNkwi.js",
  "/assets/plus-CgSXQt4h.js",
  "/assets/safeDates-ChT3SyQ_.js",
  "/assets/search-DFYfZ9zl.js",
  "/assets/send-horizontal-B73S3N8T.js",
  "/assets/smartphone-BkbH87zc.js",
  "/assets/trash-2-KWGZAD-l.js",
  "/assets/triangle-alert-Cf6hEMmg.js",
  "/favicon.ico",
  "/worker",
  "/worker-icon-192.png",
  "/worker-icon-512.png",
  "/worker-manifest.json",
  "/worker.html"
];
const PRECACHE_URL_SET = new Set(PRECACHE_URLS);
const WORKER_NAVIGATION_PATHS = ["/worker", "/worker.html", "/w/"];

async function putCacheResponse(cache, request, response) {
  if (!response || response.status >= 400) return response;
  await cache.put(request, response.clone());
  return response;
}

async function precacheAll() {
  const cache = await caches.open(CACHE_NAME);
  await Promise.all(PRECACHE_URLS.map(async (url) => {
    try {
      await cache.add(new Request(url, { cache: "reload" }));
    } catch (error) {
      console.warn("[BonGest Worker SW] Unable to precache", url, error);
    }
  }));
}

function isSameOrigin(requestUrl) {
  return requestUrl.origin === self.location.origin;
}

function shouldBypassRequest(request, requestUrl) {
  if (request.method !== "GET") return true;
  if (!isSameOrigin(requestUrl)) return true;
  if (requestUrl.pathname.includes("/~oauth")) return true;
  if (
    requestUrl.pathname.startsWith("/functions/v1/") ||
    requestUrl.pathname.startsWith("/auth/v1/") ||
    requestUrl.pathname.startsWith("/rest/v1/") ||
    requestUrl.pathname.startsWith("/storage/v1/")
  ) {
    return true;
  }
  return false;
}

function isWorkerNavigation(request, requestUrl) {
  if (request.mode !== "navigate") return false;
  return WORKER_NAVIGATION_PATHS.some((path) => (
    path.endsWith("/") ? requestUrl.pathname.startsWith(path) : requestUrl.pathname === path
  ));
}

function isPrecachedUrl(requestUrl) {
  return PRECACHE_URL_SET.has(requestUrl.pathname);
}

async function staleWhileRevalidate(event, request) {
  const cache = await caches.open(CACHE_NAME);
  const cached = await cache.match(request);
  const networkPromise = fetch(request)
    .then((response) => putCacheResponse(cache, request, response))
    .catch(() => null);

  if (cached) {
    event.waitUntil(networkPromise);
    return cached;
  }

  const response = await networkPromise;
  if (response) return response;
  return Response.error();
}

async function workerNavigationResponse(event, request) {
  const cache = await caches.open(CACHE_NAME);
  const cachedShell = await cache.match("/worker.html") || await cache.match("/worker");
  const networkPromise = fetch(request)
    .then((response) => putCacheResponse(cache, request, response))
    .catch(() => null);

  if (cachedShell) {
    event.waitUntil(networkPromise);
    return cachedShell;
  }

  const response = await networkPromise;
  if (response) return response;
  return Response.error();
}

self.addEventListener("install", (event) => {
  event.waitUntil(precacheAll());
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys
      .filter((key) => key.startsWith(CACHE_PREFIX) && key !== CACHE_NAME)
      .map((key) => caches.delete(key)));
    await self.clients.claim();
  })());
});

self.addEventListener("fetch", (event) => {
  const requestUrl = new URL(event.request.url);
  if (shouldBypassRequest(event.request, requestUrl)) return;

  if (isWorkerNavigation(event.request, requestUrl)) {
    event.respondWith(workerNavigationResponse(event, event.request));
    return;
  }

  if (isPrecachedUrl(requestUrl)) {
    event.respondWith(staleWhileRevalidate(event, event.request));
  }
});
