/* This file is generated by vite.config.ts. Do not edit dist/sw.js directly. */
const CACHE_PREFIX = "bongest-worker-precache-";
const CACHE_NAME = `${CACHE_PREFIX}560a3186a0dd`;
const PRECACHE_URLS = [
  "/app-manual/assets/WorkerApp-DZhgS1hB.js",
  "/app-manual/assets/arrow-left-BXhZDciM.js",
  "/app-manual/assets/clock-DzdbX2WY.js",
  "/app-manual/assets/format-nw6Vwo3v.js",
  "/app-manual/assets/fr-CLFRHn7i.js",
  "/app-manual/assets/image-TtqBpmWK.js",
  "/app-manual/assets/interventionReferences-rTpzSBNm.js",
  "/app-manual/assets/isToday-BR9N-pZS.js",
  "/app-manual/assets/loader-circle-CV6udhFr.js",
  "/app-manual/assets/main-CNMGtfHj.css",
  "/app-manual/assets/main-Ddknt1oI.js",
  "/app-manual/assets/package-DX2TKmk4.js",
  "/app-manual/assets/phone-BdizEoVa.js",
  "/app-manual/assets/plus-CQTbuR79.js",
  "/app-manual/assets/safeDates-BcnN1mUj.js",
  "/app-manual/assets/search-DJ5KDI4c.js",
  "/app-manual/assets/send-horizontal-BRtIPA9u.js",
  "/app-manual/assets/smartphone-DrlwrcgE.js",
  "/app-manual/assets/trash-2-NOoNp0DP.js",
  "/app-manual/assets/triangle-alert-aWRQe3BN.js",
  "/app-manual/worker-icon-192.png",
  "/app-manual/worker-icon-512.png",
  "/app-manual/worker-manifest.json",
  "/favicon.ico",
  "/worker",
  "/worker-icon-192.png",
  "/worker-icon-512.png",
  "/worker-manifest.json",
  "/worker.html"
];
const PRECACHE_URL_SET = new Set(PRECACHE_URLS);
const WORKER_NAVIGATION_PATHS = ["/worker", "/worker.html", "/w/"];

async function putCacheResponse(cache, request, response) {
  if (!response || response.status >= 400) return response;
  await cache.put(request, response.clone());
  return response;
}

async function precacheAll() {
  const cache = await caches.open(CACHE_NAME);
  await Promise.all(PRECACHE_URLS.map(async (url) => {
    try {
      await cache.add(new Request(url, { cache: "reload" }));
    } catch (error) {
      console.warn("[BonGest Worker SW] Unable to precache", url, error);
    }
  }));
}

function isSameOrigin(requestUrl) {
  return requestUrl.origin === self.location.origin;
}

function shouldBypassRequest(request, requestUrl) {
  if (request.method !== "GET") return true;
  if (!isSameOrigin(requestUrl)) return true;
  if (requestUrl.pathname.includes("/~oauth")) return true;
  if (
    requestUrl.pathname.startsWith("/functions/v1/") ||
    requestUrl.pathname.startsWith("/auth/v1/") ||
    requestUrl.pathname.startsWith("/rest/v1/") ||
    requestUrl.pathname.startsWith("/storage/v1/")
  ) {
    return true;
  }
  return false;
}

function isWorkerNavigation(request, requestUrl) {
  if (request.mode !== "navigate") return false;
  return WORKER_NAVIGATION_PATHS.some((path) => (
    path.endsWith("/") ? requestUrl.pathname.startsWith(path) : requestUrl.pathname === path
  ));
}

function isPrecachedUrl(requestUrl) {
  return PRECACHE_URL_SET.has(requestUrl.pathname);
}

async function staleWhileRevalidate(event, request) {
  const cache = await caches.open(CACHE_NAME);
  const cached = await cache.match(request);
  const networkPromise = fetch(request)
    .then((response) => putCacheResponse(cache, request, response))
    .catch(() => null);

  if (cached) {
    event.waitUntil(networkPromise);
    return cached;
  }

  const response = await networkPromise;
  if (response) return response;
  return Response.error();
}

async function workerNavigationResponse(event, request) {
  const cache = await caches.open(CACHE_NAME);
  const cachedShell = await cache.match("/worker.html") || await cache.match("/worker");
  const networkPromise = fetch(request)
    .then((response) => putCacheResponse(cache, request, response))
    .catch(() => null);

  if (cachedShell) {
    event.waitUntil(networkPromise);
    return cachedShell;
  }

  const response = await networkPromise;
  if (response) return response;
  return Response.error();
}

self.addEventListener("install", (event) => {
  event.waitUntil(precacheAll());
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys
      .filter((key) => key.startsWith(CACHE_PREFIX) && key !== CACHE_NAME)
      .map((key) => caches.delete(key)));
    await self.clients.claim();
  })());
});

self.addEventListener("fetch", (event) => {
  const requestUrl = new URL(event.request.url);
  if (shouldBypassRequest(event.request, requestUrl)) return;

  if (isWorkerNavigation(event.request, requestUrl)) {
    event.respondWith(workerNavigationResponse(event, event.request));
    return;
  }

  if (isPrecachedUrl(requestUrl)) {
    event.respondWith(staleWhileRevalidate(event, event.request));
  }
});
